#!/bin/bash
set -eu

# build/expose script

LOCAL_BIN="$HOME/.local/bin"

# copy it over to local bins
[[ ! -d "$LOCAL_BIN/minienv" ]] && mkdir "$LOCAL_BIN/minienv"
cp -a minienv "$LOCAL_BIN/minienv/minienv"

# make it executable
chmod u+x "$LOCAL_BIN/minienv/minienv"

